name: ai_env
channels:
  - conda-forge
  - plotly
  - anaconda
dependencies:
  - python=3.6
  - numpy=1.19.2
  - pandas=1.1.5
  - seaborn=0.11.2
  - pathlib=1.0.1
  - plotly=5.3.1
  - matplotlib
  - scipy
  - statsmodels
  - scikit-learn
  - networkx
  - notebook
  - jupyter_contrib_nbextensions
